// Code generated by Kitex v0.3.1. DO NOT EDIT.

package videoservice

import (
	"context"
	"douyin/kitex_gen/video"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return videoServiceServiceInfo
}

var videoServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "VideoService"
	handlerType := (*video.VideoService)(nil)
	methods := map[string]kitex.MethodInfo{
		"PublishVideo":   kitex.NewMethodInfo(publishVideoHandler, newVideoServicePublishVideoArgs, newVideoServicePublishVideoResult, false),
		"GetPublishList": kitex.NewMethodInfo(getPublishListHandler, newVideoServiceGetPublishListArgs, newVideoServiceGetPublishListResult, false),
		"GetFeed":        kitex.NewMethodInfo(getFeedHandler, newVideoServiceGetFeedArgs, newVideoServiceGetFeedResult, false),
		"VerifyVideoId":  kitex.NewMethodInfo(verifyVideoIdHandler, newVideoServiceVerifyVideoIdArgs, newVideoServiceVerifyVideoIdResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "video",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.3.1",
		Extra:           extra,
	}
	return svcInfo
}

func publishVideoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServicePublishVideoArgs)
	realResult := result.(*video.VideoServicePublishVideoResult)
	success, err := handler.(video.VideoService).PublishVideo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServicePublishVideoArgs() interface{} {
	return video.NewVideoServicePublishVideoArgs()
}

func newVideoServicePublishVideoResult() interface{} {
	return video.NewVideoServicePublishVideoResult()
}

func getPublishListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceGetPublishListArgs)
	realResult := result.(*video.VideoServiceGetPublishListResult)
	success, err := handler.(video.VideoService).GetPublishList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceGetPublishListArgs() interface{} {
	return video.NewVideoServiceGetPublishListArgs()
}

func newVideoServiceGetPublishListResult() interface{} {
	return video.NewVideoServiceGetPublishListResult()
}

func getFeedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceGetFeedArgs)
	realResult := result.(*video.VideoServiceGetFeedResult)
	success, err := handler.(video.VideoService).GetFeed(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceGetFeedArgs() interface{} {
	return video.NewVideoServiceGetFeedArgs()
}

func newVideoServiceGetFeedResult() interface{} {
	return video.NewVideoServiceGetFeedResult()
}

func verifyVideoIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceVerifyVideoIdArgs)
	realResult := result.(*video.VideoServiceVerifyVideoIdResult)
	success, err := handler.(video.VideoService).VerifyVideoId(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceVerifyVideoIdArgs() interface{} {
	return video.NewVideoServiceVerifyVideoIdArgs()
}

func newVideoServiceVerifyVideoIdResult() interface{} {
	return video.NewVideoServiceVerifyVideoIdResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PublishVideo(ctx context.Context, req *video.PublishVideoRequest) (r *video.PublishVideoResponse, err error) {
	var _args video.VideoServicePublishVideoArgs
	_args.Req = req
	var _result video.VideoServicePublishVideoResult
	if err = p.c.Call(ctx, "PublishVideo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPublishList(ctx context.Context, req *video.GetPublishListRequest) (r *video.GetPublishListResponse, err error) {
	var _args video.VideoServiceGetPublishListArgs
	_args.Req = req
	var _result video.VideoServiceGetPublishListResult
	if err = p.c.Call(ctx, "GetPublishList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFeed(ctx context.Context, req *video.GetFeedRequest) (r *video.GetFeedResponse, err error) {
	var _args video.VideoServiceGetFeedArgs
	_args.Req = req
	var _result video.VideoServiceGetFeedResult
	if err = p.c.Call(ctx, "GetFeed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyVideoId(ctx context.Context, req *video.VerifyVideoIdResponse) (r *video.VerifyVideoIdRequest, err error) {
	var _args video.VideoServiceVerifyVideoIdArgs
	_args.Req = req
	var _result video.VideoServiceVerifyVideoIdResult
	if err = p.c.Call(ctx, "VerifyVideoId", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
