// Code generated by Kitex v0.3.1. DO NOT EDIT.
package thumbservice

import (
	"github.com/cloudwego/kitex/server"
	"github.com/yanhongsun/douyin/douyin/kitex_gen/like"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler like.ThumbService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
